format:
  lgr-pdf:
    keep-tex: false

project:
  type: book
  output-dir: ../_pdf/

book:
  chapters:
#     - ../index.qmd
#     - ../intro.qmd
    - index.qmd
    - 1 Introducao/00-Racismo-Ideologia-Propostas-e-o-Artista.md
    - 1 Introducao/01-Perfil-Da-Literatura-Negra.md
    - part: "Literatura Brasileira"
      chapters:
        - 2 Literatura Brasileira/00-O-Negro-Na-Literatura-Brasileira.md
        - 2 Literatura Brasileira/01-Entrevista-Leon-Damas-e-a-Negritude-Brasileira.md
        - 2 Literatura Brasileira/02-Invencoes-e-Algemas-De-Castro-Alves.md
        - 2 Literatura Brasileira/03-O-Mulato-Raimundo-Faz-Cem-Anos.md
        - 2 Literatura Brasileira/04-Resenha-De-Lgr-Vetada-e-Nao-Publicada-No-Jt-Sobre-Adolfo-Caminha.md
        - 2 Literatura Brasileira/05-A-Revolta-De-Um-Precursor.md
        - 2 Literatura Brasileira/06-Lima-Barreto-Altamente-Inovador-e-Quase-Desconhecido.md
        - 2 Literatura Brasileira/07-Lima-Barreto-Doce-Feroz-Iluminado-e-Esquecido.md
        - 2 Literatura Brasileira/08-Policarpo-Quaresma-Uma-Obra-Prima-Envolta-Em-Doce-Amargura.md
        - 2 Literatura Brasileira/09-A-Mae-Coragem-Negra-De-Caninde-Sobre-Os-Diarios-De-Carolina-Maria-De-Jesus.md
        - 2 Literatura Brasileira/10-O-Negro-Nos-Livros-Poemas-e-Teses.md
        - 2 Literatura Brasileira/11-Poesia-Uma-Obra-Reunindo-Poetas-Negros-De-Varias-Epocas.md
        - 2 Literatura Brasileira/12-Nossa-Poesia-Negra-Tentando-Falar-Alemao.md
        - 2 Literatura Brasileira/13-O-Evangelho-Da-Solidao-De-Eduardo-De-Oliveira.md
        - 2 Literatura Brasileira/14-Prefacio-Ao-Livro-De-Paulo-Colina.md
        - 2 Literatura Brasileira/15-Paulo-Colina-o-Poeta-Das-Cinzas.md
    - part: "Literatura Norte-Americana"
      chapters:
        - 3 Literatura Norte-Americana/00-Literatura-Negra-Nos-Estados-Unidos-James-Baldwin.md
        - 3 Literatura Norte-Americana/01-James-Baldwin-e-o-Negro-Nos-Eua.md
        - 3 Literatura Norte-Americana/02-o-Negro-Baldwin-Luta-Pelos-Seus.md
        - 3 Literatura Norte-Americana/03-James-Baldwin-(Necrologio).md
        - 3 Literatura Norte-Americana/04-Resenha-Do-Livro-o-Mensageiro-de-Charles-Wright-(Editora-Nova-Critica-1969).md
        - 3 Literatura Norte-Americana/05-A-Influência-Decisiva-de-Richard-Wright.md
        - 3 Literatura Norte-Americana/06-Entrevista-Toni-Morrison-e-Os-Negros-Da-America.md
        - 3 Literatura Norte-Americana/07-Nota-Sobre-o-Livro-o-Olho-Mais-Azul-de-Toni-Morrison.md
    - part: "Literatura Africana"
      chapters:
        - 4 Literatura Africana/00-A-Africa-Em-Lendas-e-Contos-Lembrando-Nossa-Historia.md
        - 4 Literatura Africana/01-A-Negritude-Transfiguracao-Poetica-Do-Rosto-Africano.md
        - 4 Literatura Africana/02-Angola-Escreve-Uma-Arte-Magica-e-Sofrida-Vinda-de-Onde-Nao-Se-Sabe.md
        - 4 Literatura Africana/03-Angola-Escreve-Alguns-Grandes-Autores-Do-Romance-Ao-Conto.md
        - 4 Literatura Africana/04-A-Africa-e-a-Liberdade-Entrevista-Com-Luandino-Vieira.md
        - 4 Literatura Africana/05-Angola-Num-Momento-de-Reflexoes-e-Mudancas-Entrevista-Com-o-Escritor-Angolano-Agostinho-Mendes.md
        - 4 Literatura Africana/06-A-Ultima-Denuncia-de-Soromenho.md
        - 4 Literatura Africana/07-Senghor-o-Orfeu-Negro.md
        - 4 Literatura Africana/08-Resenha-Sobre-Poemas-de-Senghor.md
        - 4 Literatura Africana/09-a-Poesia-Nao-Deve-Morrer-Senao-Que-Esperanca-Restaria-Ao-Mundo.md
        - 4 Literatura Africana/10-Sebene-Ousmane-Do-Senegal-Um-Importante-Momento-Da-Literatura-Africana-Mas-a-Traducao.md
        - 4 Literatura Africana/11-a-Africa-Hoje-Em-Dois-Bons-Livros-Lgr-Comenta-As-Obras-de-Chinua-Achebe-e-Cyprian-Ekwensi.md
        - 4 Literatura Africana/12-o-Negro-e-a-Cultura-de-Mocambique-Nao-Merecem-Romance-Tao-Ruim-Quanto-Este.md
        - 4 Literatura Africana/13-Resenha-Do-Livro-Um-Fuzil-Na-Mao-Um-Poema-No-Bolso-de-Emmanuel-Dongala.md
        - 4 Literatura Africana/14-Um-Nobel-Para-a-Africa-Wole-Soyinka.md
        - 4 Literatura Africana/15-Nota-Sobre-o-Livro-a-Arma-Da-Casa-de-Nadine-Gordimer.md
        - 4 Literatura Africana/16-Nota-Sobre-o-Livro-Desonra-de-J-M-Coetzee.md
