site_name: Léo Gilson Ribeiro
copyright: 
site_description: Obras reunidas de Léo Gilson Ribeiro
repo_name: bcdavasconcelos/LGR
repo_url: https://github.com/bcdavasconcelos/LGR
edit_uri: tree/main
docs_dir: docs/src/markdown/
theme:
  name: material
  custom_dir: docs/theme
  language: pt-BR
  font:
    text: Alegreya
    code: Inconsolata
  favicon: 
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/git-alt
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  features:
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
plugins:
  - git-revision-date-localized:
      type: iso_date
      locale: pt
      timezone: America/Sao_Paulo
  - minify:
     minify_html: true
  - search:
      lang: pt
  - tags:
      tags_file: tags.md
  - redirects:
      redirect_maps:


markdown_extensions:
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - markdown.extensions.smarty:
      smart_quotes: false
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: ""
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'
  - pymdownx.betterem:
  - pymdownx.caret:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {kwds: {mode: generic}}
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.striphtml:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:

nav:
  - Racismo e literatura negra:
    - Racismo e literatura negra: racismo-e-literatura-negra/README.md
    - Introdução:
      - Introdução: racismo-e-literatura-negra/introdu-o/README.md
      - Racismo, ideologia, propostas. E o artista?: racismo-e-literatura-negra/introdu-o/racismo-ideologia-propostas-e-o-artista-.md
      - Perfil da Literatura Negra: racismo-e-literatura-negra/introdu-o/perfil-da-literatura-negra.md
    - Literatura Brasileira:
      - Literatura Brasileira: racismo-e-literatura-negra/literatura-brasileira/README.md
      - O negro na literatura brasileira: racismo-e-literatura-negra/literatura-brasileira/o-negro-na-literatura-brasileira.md
      - Entrevista - León Damas e a Negritude brasileira: racismo-e-literatura-negra/literatura-brasileira/entrevista---le-n-damas-e-a-negritude-brasileira.md
      - Invenções e algemas de Castro Alves: racismo-e-literatura-negra/literatura-brasileira/inven-es-e-algemas-de-castro-alves.md
      - O mulato Raimundo faz cem anos: racismo-e-literatura-negra/literatura-brasileira/o-mulato-raimundo-faz-cem-anos.md
      - Resenha de LGR vetada e não publicada no *JT* sobre Adolfo Caminha: racismo-e-literatura-negra/literatura-brasileira/resenha-de-lgr-vetada-e-n-o-publicada-no-jt-sobre-.md
      - A revolta de um precursor: racismo-e-literatura-negra/literatura-brasileira/a-revolta-de-um-precursor.md
      - Lima Barreto - altamente inovador. E quase desconhecido.: racismo-e-literatura-negra/literatura-brasileira/lima-barreto---altamente-inovador-e-quase-desconhe.md
      - Lima Barreto - doce, feroz, iluminado. E esquecido.: racismo-e-literatura-negra/literatura-brasileira/lima-barreto---doce-feroz-iluminado-e-esquecido-.md
      - Policarpo Quaresma, uma obra-prima envolta em doce amargura: racismo-e-literatura-negra/literatura-brasileira/policarpo-quaresma-uma-obra-prima-envolta-em-doce-.md
      - A Mãe Coragem negra de Canindé. Sobre os diários de Carolina Maria de Jesus: racismo-e-literatura-negra/literatura-brasileira/a-m-e-coragem-negra-de-canind-sobre-os-di-rios-de-.md
      - O negro nos livros, poemas e teses: racismo-e-literatura-negra/literatura-brasileira/o-negro-nos-livros-poemas-e-teses.md
      - Poesia. Uma obra reunindo poetas negros de várias épocas: racismo-e-literatura-negra/literatura-brasileira/poesia-uma-obra-reunindo-poetas-negros-de-v-rias-p.md
      - Nossa poesia negra, tentando falar alemão: racismo-e-literatura-negra/literatura-brasileira/nossa-poesia-negra-tentando-falar-alem-o.md
      - O Evangelho da Solidão de Eduardo de Oliveira: racismo-e-literatura-negra/literatura-brasileira/o-evangelho-da-solid-o-de-eduardo-de-oliveira.md
      - Prefácio ao livro de Paulo Colina: racismo-e-literatura-negra/literatura-brasileira/pref-cio-ao-livro-de-paulo-colina.md
      - Paulo Colina - o poeta das cinzas: racismo-e-literatura-negra/literatura-brasileira/paulo-colina---o-poeta-das-cinzas.md
    - Literatura Norte-americana:
      - Literatura Norte-americana: racismo-e-literatura-negra/literatura-norte-americana/README.md
      - Literatura negra nos Estados Unidos - James Baldwin: racismo-e-literatura-negra/literatura-norte-americana/literatura-negra-nos-estados-unidos---james-baldwi.md
      - James Baldwin e o negro nos EUA: racismo-e-literatura-negra/literatura-norte-americana/james-baldwin-e-o-negro-nos-eua.md
      -  O negro Baldwin luta pelos seus: racismo-e-literatura-negra/literatura-norte-americana/-o-negro-baldwin-luta-pelos-seus.md
      - James Baldwin (necrológio): racismo-e-literatura-negra/literatura-norte-americana/james-baldwin-necrol-gio-.md
      - Resenha do livro *O Mensageiro* de Charles Wright(Editora Nova Crítica, 1969) : racismo-e-literatura-negra/literatura-norte-americana/resenha-do-livro-o-mensageiro-de-charles-wright-ed.md
      - A influência decisiva de Richard Wright: racismo-e-literatura-negra/literatura-norte-americana/a-influ-ncia-decisiva-de-richard-wright.md
      - Entrevista - Toni Morrison e os negros da América: racismo-e-literatura-negra/literatura-norte-americana/entrevista---toni-morrison-e-os-negros-da-am-rica.md
      - Nota sobre o livro *O Olho mais Azul* de Toni Morrison: racismo-e-literatura-negra/literatura-norte-americana/nota-sobre-o-livro-o-olho-mais-azul-de-toni-morris.md
    - Literatura Africana:
      - Literatura Africana: racismo-e-literatura-negra/literatura-africana/README.md
      - A África em lendas e contos. Lembrando nossa História: racismo-e-literatura-negra/literatura-africana/a-frica-em-lendas-e-contos-lembrando-nossa-hist-ri.md
      - A Negritude -- Transfiguração Poética do Rosto Africano: racismo-e-literatura-negra/literatura-africana/a-negritude----transfigura-o-po-tica-do-rosto-afri.md
      - Angola escreve. Uma arte mágica e sofrida vinda de onde não se sabe.: racismo-e-literatura-negra/literatura-africana/angola-escreve-uma-arte-m-gica-e-sofrida-vinda-de-.md
      - Angola Escreve. Alguns grandes autores do romance ao conto.: racismo-e-literatura-negra/literatura-africana/angola-escreve-alguns-grandes-autores-do-romance-a.md
      - A África e a liberdade. Entrevista com Luandino Vieira: racismo-e-literatura-negra/literatura-africana/a-frica-e-a-liberdade-entrevista-com-luandino-viei.md
      - Angola, num momento de reflexões e mudanças. Entrevista com o escritor angolano Agostinho Mendes: racismo-e-literatura-negra/literatura-africana/angola-num-momento-de-reflex-es-e-mudan-as-entrevi.md
      - A última denúncia de Soromenho: racismo-e-literatura-negra/literatura-africana/a-ltima-den-ncia-de-soromenho.md
      - Senghor, o Orfeu negro: racismo-e-literatura-negra/literatura-africana/senghor-o-orfeu-negro.md
      - Resenha sobre *Poemas* de Senghor: racismo-e-literatura-negra/literatura-africana/resenha-sobre-poemas-de-senghor.md
      - "A poesia não deve morrer. Senão, que esperança restaria ao mundo?": racismo-e-literatura-negra/literatura-africana/-a-poesia-n-o-deve-morrer-sen-o-que-esperan-a-rest.md
      - Sebène Ousmane do Senegal. Um importante momento da literatura africana. Mas a tradução\...: racismo-e-literatura-negra/literatura-africana/seb-ne-ousmane-do-senegal-um-importante-momento-da.md
      - A África, hoje. Em dois bons livros. LGR comenta as obras de Chinua Achebe e Cyprian Ekwensi: racismo-e-literatura-negra/literatura-africana/a-frica-hoje-em-dois-bons-livros-lgr-comenta-as-ob.md
      - O negro e a cultura de Moçambique não merecem romance tão ruim quanto este: racismo-e-literatura-negra/literatura-africana/o-negro-e-a-cultura-de-mo-ambique-n-o-merecem-roma.md
      - Resenha do livro - *Um fuzil na mão um poema no bolso* de Emmanuel Dongala: racismo-e-literatura-negra/literatura-africana/resenha-do-livro---um-fuzil-na-m-o-um-poema-no-bol.md
      - Um Nobel para a África - Wole Soyinka: racismo-e-literatura-negra/literatura-africana/um-nobel-para-a-frica---wole-soyinka.md
      - Nota sobre o livro *A Arma da Casa* de Nadine Gordimer: racismo-e-literatura-negra/literatura-africana/nota-sobre-o-livro-a-arma-da-casa-de-nadine-gordim.md
      - Nota sobre o livro *Desonra* de J. M. Coetzee: racismo-e-literatura-negra/literatura-africana/nota-sobre-o-livro-desonra-de-j-m-coetzee.md
  - Tags: tags.md


extra_css:
  - assets/extra.css
  - assets/pymdownx-extras/extra.css

extra_javascript:
  - assets/js/tablesort.js
  - assets/pymdownx-extras/extra-loader.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mermaid@8.13.3/dist/mermaid.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
