format:
  lgr-pdf

project:
  type: book
  output-dir: ../_pdf/

book:
  chapters:
    - index.qmd
    - part: "Brasil-Portugal - tentativas de aproximação"
      chapters:
        - 01-Brasil--Portugal-Tentativas-de-Aproximação/00-Na-Contramao.md
        - 01-Brasil--Portugal-Tentativas-de-Aproximação/01-Poetas-Portugueses-Versos-e-Duas-Culturas-Reencontram-Seu-Ponto-de-Uniao.md
        - 01-Brasil--Portugal-Tentativas-de-Aproximação/02-Um-Encontro-de-Portugal-e-Brasil-Sobre-a-Liberdade.md
    - part: "Fernão Mendes Pinto"
      chapters:
        - 02-Fernão-Mendes-Pinto/00-a-Fascinante-Aventura-Do-Marco-Polo-Portugues.md
    - part: "Eça de Queirós"
      chapters:
        - 03-Eça-de-Queiros/00-Tese-e-Antitese-de-Eca-de-Queiros.md
        - 03-Eça-de-Queiros/01-Suave-Milagre-No-Fim-Da-Vida-Um-Eca-Religioso.md
        - 03-Eça-de-Queiros/02-Depois-Dele-Portugal-Nao-Foi-Mais-o-Mesmo-Nem-o-Portugues.md
        - 03-Eça-de-Queiros/03-Uma-Obra-Prima-Inacabada-Com-a-Marca-Da-Grandeza-Olimpica-de-Eca.md
        - 03-Eça-de-Queiros/04-Eca-de-Queiros-Cem-Anos-de-Sua-Morte.md
    - part: "Antero de Quental"
      chapters:
        - 04-Antero-de-Quental/00-Antero-de-Quental-o-Ideal-Estetico-e-Politico.md
    - part: "Antônio Lobo Antunes"
      chapters:
        - 05-Antônio-Lobo-Antunes/00-a-Ousadia-Deste-Irreverente-Escritor-Portugues.md
    - part: "Antônio José Saraiva"
      chapters:
        - 06-Antônio-José-Saraiva/00-Entrevista-Com-Antonio-Jose-Saraiva.md
    - part: "Manuel Ferreira"
      chapters:
        - 07-Manuel-Ferreira/00-Manuel-Ferreira-a-Bondade-e-a-Opressao.md
    - part: "Antônio Alçada Baptista"
      chapters:
        - 08-Antônio-Alcada-Baptista/00-Um-Feminismo-Sutil-Sucesso-Em-Portugal.md
    - part: "Ferreira de Castro"
      chapters:
        - 09-Ferreira-de-Castro/00-As-Novas-Dimensoes-Do-Realismo-Literario-(A-Selva-de-Ferreira-de-Castro).md
    - part: "Teixeira de Pascoais"
      chapters:
        - 10-Teixeira-de-Pascoais/00-Um-Poeta-Mistico-Na-Era-Atomica.md
    - part: "Fernando Namora"
      chapters:
        - 11-Fernando-Namora/00-Fernando-Namora.md
    - part: "Fernando Pessoa"
      chapters:
        - 12-Fernando-Pessoa/00-Fernando-Pessoa-I.md
        - 12-Fernando-Pessoa/01-Fernando-Pessoa-Ii-Fotobiografias.md
        - 12-Fernando-Pessoa/02-Fernando-Pessoa-Iii-o-Poeta-Singular-e-Plural-de-Joao-Alves-Das-Neves-(Editora-Expressao).md
        - 12-Fernando-Pessoa/03-Entrevista-Com-Joao-Gaspar-Simoes-o-Poeta-e-a-Humanidade.md
    - part: "Vergílio Ferreira"
      chapters:
        - 13-Vergílio-Ferreira/00-Entrevista-a-Vergilio-Ferreira.md
        - 13-Vergílio-Ferreira/01-Destruindo-a-Palavra-Para-Reencontra-La-Mais-Bela-e-Pura.md
    - part: "Eugênio de Andrade"
      chapters:
        - 14-Eugênio-de-Andrade/00-o-Amor-Erotico-de-Eugenio-de-Andrade-Delicado-Audaz.md
    - part: "José Cardoso Pires"
      chapters:
        - 15-José-Cardoso-Pires/00-Eis-Um-Grande-Escritor.md
        - 15-José-Cardoso-Pires/01-Uma-Entrevista-Com-o-Maior-Escritor-Portugues-Do-Momento.md
        - 15-José-Cardoso-Pires/02-Cardoso-Pires-Para-Quando-o-Brasil-Descobrir-Portugal.md
        - 15-José-Cardoso-Pires/03-a-Tardia-Descoberta-de-Um-Polemico-Escritor-Portugues.md
        - 15-José-Cardoso-Pires/04-Cardoso-Pires-Reinventa-Portugal.md
        - 15-José-Cardoso-Pires/05-Desafiando-Os-Rinocerontes-Do-Poder.md
    - part: "José Saramago"
      chapters:
        - 16-José-Saramago/00-Saramago.md
        - 16-José-Saramago/01-Um-Deus-Sadico-Martiriza-Sua-Marionete-Jesus.md
    - part: "Três breves notícias sobre escritores ou livros portugueses"
      chapters:
        - 17-Três-Breves-Notícias-sobre-Escritores-ou-Livros-Portugueses/00-Casais-Monteiro.md
        - 17-Três-Breves-Notícias-sobre-Escritores-ou-Livros-Portugueses/01-De-Maria-Isabel-Barreno-Maria-Teresa-Horta-e-Maria-Velho-Da-Costa.md
        - 17-Três-Breves-Notícias-sobre-Escritores-ou-Livros-Portugueses/02-Os-Novos-Tempos-de-Portugal.md
