format:
  lgr-pdf

project:
  type: book
  output-dir: ../_pdf/

filters:
  - fontawesome
  - lgr

book:
  chapters:
    - index.qmd
    - part: "Virginia Woolf"
      chapters:
        - 01-virginia-woolf/00-arte-amor-morte.md
        - 01-virginia-woolf/01-ela-foi-muito-mal-recebida-no-brasil-pelo-tradutor.md
        - 01-virginia-woolf/02-o-retrato-de-virginia-woolf-a-luta-de-uma-escritora-angustiada-com-o-efemero.md
        - 01-virginia-woolf/03-virginia-woolf-pensamentos-ainda-brilhantes-40-anos-depois.md
        - 01-virginia-woolf/04-woolf-ainda-um-enigma-(a-outra-metade-do-artigo-sobre-yourcenar-sera-transcrito-na-proxima-secao-consagrada-a-escritora-belga).md
        - 01-virginia-woolf/05-virginia-woolf-anotacoes-vividas-de-uma-estilista-perfeita.md
    - part: "Marguerite Yourcenar"
      chapters:
        - 02-marguerite-yourcenar/00-yourcenar-na-academia-um-premio-para-a-mulher.md
        - 02-marguerite-yourcenar/01-a-agonia-tragica-e-solene-de-adriano-num-livro-deslumbrante.md
        - 02-marguerite-yourcenar/02-uma-viagem-ao-reino-da-dor-do-amor-do-poder-da-morte.md
        - 02-marguerite-yourcenar/03-yourcenar-sempre-pioneira-(segunda-metade-do-artigo-cuja-primeira-parte-inserimos-na-secao-acima-consagrada-a-virginia-woolf).md
        - 02-marguerite-yourcenar/04-e-fica-o-brilho-de-marguerite-yourcenar.md
    - part: "Doris Lessing"
      chapters:
        - 03-doris-lessing/00-doris-lessing-brilhante-apesar-da-ma-traducao.md
        - 03-doris-lessing/01-tragica-lucida-renovadora-doris-lessing.md
        - 03-doris-lessing/02-multipla-doris-lessing.md
        - 03-doris-lessing/03-o-teorema-espacial-de-doris-lessing-longo-e-belo.md
        - 03-doris-lessing/04-doris-lessing-de-1952-apenas-uma-lembranca-arqueologica.md
        - 03-doris-lessing/05-doris-lessing-derrubando-mitos.md
        - 03-doris-lessing/06-doris-lessing-grandiosa-vital.md
        - 03-doris-lessing/07-doris-lessing-uma-rapsodia-esplendida-prisma-da-condicao-humana.md
        - 03-doris-lessing/08-doris-lessing-a-dama-de-ferro-da-literatura-inglesa.md
        - 03-doris-lessing/09-doris-lessing-a-solitaria-grendeza-de-uma-estilista.md
        - 03-doris-lessing/10-doris-lessing-mais-uma-vez-fascinante.md
        - 03-doris-lessing/11-doris-lessing.md
        - 03-doris-lessing/12-a-visita-da-majestosa-senhora.md
        - 03-doris-lessing/13-entrevista-a-doris-lessing-o-triunfo-da-inteligencia-sem-dogmas.md
        - 03-doris-lessing/14-lessing-na-trilha-do-horror.md
