AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 280

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 30

Metrics/ClassLength:
  Enabled: true
  CountComments: false
  Max: 30

Metrics/AbcSize:
  Enabled: true
  Max: 20
