<!-- begin_file: "_quarto.yml" -->
  
[]{#scriv26}
Block
> Block Quote  
Body

:::{.callout-caution}
Callout Caution
:::

:::{.callout-important}
Callout Important
:::

:::{.callout-note}
Callout Note
:::

:::{.callout-tip}
Callout Tip
:::

:::{.callout-warning}
Callout Warning
:::

Caption
~~~
Code Block
~~~
:::{.column-page}
Column Page
:::

::: {#cnj-scriv26}
Crossref Conjecture
:::

::: {#cor-scriv26}
Crossref Corollary
:::

::: {#def-scriv26}
Crossref Definition
:::

::: {#exm-scriv26}
Crossref Example
:::

::: {#exr-scriv26}
Crossref Exercise
:::

Crossref Label
::: {#lem-scriv26}
Crossref Lemma
:::

::: {#prp-scriv26}
Crossref Proposition
:::

::: {#thm-scriv26}
Crossref Theorem
:::

```{dot}
Dot Block
```
Generic Code
# Heading 1

## Heading 2 

### Header 3

List
:::{.column-margin}
Marginalia
:::

$$Maths Block$$
```{mermaid}
Mermaid Block
```

Meta-data
```{python}
Python Block
```

```{r}
R Block
```

~~~{=html}
Raw HTML
~~~

~~~{=latex}
Raw LaTeX
~~~

~~~ruby
Ruby Code
~~~
Table Caption
Table Text

<!-- end_file -->
  
